sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: yn


  alioss:
    access-key-id: LTAI5t6YrTDt8wvn9N921b9P
    access-key-secret: QKiw1vTxuvWMhZ3tu464Fr5L1uMZ47
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: yn-sky
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx7eb65c9f9c946a1d
    secret: 5fa09cfde98ddeb1daaa7656760776e1
